version: '3.8'
services:
  sodateru-postgres:
    image: 201610615/sodateru-postgres:v0.0.0
    ports:
      - "8989:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: